import "server-only";
import type { ScoreResult } from "@/lib/scoring/engine";
import { tierFor } from "@/lib/reputation";

export interface AgentSummary {
  strengths: string[];
  risks: string;
  recommendation: string;
  /** "ai" when generated by Claude, "template" for the deterministic fallback. */
  source: "ai" | "template";
}

/**
 * Generate the human-readable reputation summary. Uses Claude when
 * ANTHROPIC_API_KEY is configured; otherwise returns a deterministic template
 * so the product is fully functional without an LLM.
 *
 * Security notes:
 *  - runs server-only; the API key never reaches the client
 *  - the model is asked for STRICT JSON and the output is parsed, never
 *    rendered as HTML, so a prompt-injected response cannot inject markup
 */
export async function generateSummary(
  name: string,
  result: ScoreResult,
): Promise<AgentSummary> {
  const key = process.env.ANTHROPIC_API_KEY;
  if (!key) return templateSummary(name, result);

  try {
    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "x-api-key": key,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
      },
      body: JSON.stringify({
        model: "claude-haiku-4-5",
        max_tokens: 500,
        messages: [
          {
            role: "user",
            content:
              `You are a crypto reputation analyst. Given this AI agent's scores ` +
              `(0-100), return STRICT JSON with keys "strengths" (array of 3 short ` +
              `strings), "risks" (one paragraph), "recommendation" (one sentence). ` +
              `No markdown, no extra text.\n\nAgent: ${name}\nScores: ${JSON.stringify(result.scores)}\nTrust: ${result.trustScore}`,
          },
        ],
      }),
    });
    if (!res.ok) throw new Error(`Anthropic ${res.status}`);
    const data = (await res.json()) as { content?: { text?: string }[] };
    const text = data.content?.[0]?.text ?? "";
    const parsed = JSON.parse(text) as Omit<AgentSummary, "source">;
    return { ...parsed, source: "ai" };
  } catch {
    return templateSummary(name, result);
  }
}

function templateSummary(name: string, result: ScoreResult): AgentSummary {
  const { scores, trustScore } = result;
  const strong = (Object.entries(scores) as [string, number][])
    .filter(([, v]) => v >= 70)
    .map(([k]) => k);
  const weak = (Object.entries(scores) as [string, number][])
    .filter(([, v]) => v < 50)
    .map(([k]) => k);
  const tier = tierFor(trustScore);

  return {
    source: "template",
    strengths: [
      strong.length
        ? `Strong ${strong.join(", ")} signals anchor the overall profile.`
        : "Balanced signal profile across all dimensions.",
      `Developer score of ${scores.developer}/100 reflects current shipping cadence.`,
      `Security score of ${scores.security}/100 from contract & ownership checks.`,
    ],
    risks: weak.length
      ? `Elevated risk in ${weak.join(", ")}. Monitor these dimensions before relying on ${name} for autonomous tasks.`
      : `No critical weaknesses detected, though all metrics warrant ongoing monitoring.`,
    recommendation:
      trustScore >= 70
        ? `${name} is a ${tier.label.toLowerCase()} agent; metrics support continued engagement with routine monitoring.`
        : `${name} carries elevated risk; treat as speculative until signals stabilize.`,
  };
}
